// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBLDVZESlV9jDfm6wDDXMZytf9FSfECMc',
    appId: '1:1027150286660:web:a70c006470e5f4ec16d111',
    messagingSenderId: '1027150286660',
    projectId: 'shm-app-9927d',
    authDomain: 'shm-app-9927d.firebaseapp.com',
    storageBucket: 'shm-app-9927d.firebasestorage.app',
    measurementId: 'G-5EF7RVWR1P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAT_AcH7VyM0JpaJGbZcmvnFOg_0KP9RDA',
    appId: '1:1027150286660:android:234bc06dc5c5263316d111',
    messagingSenderId: '1027150286660',
    projectId: 'shm-app-9927d',
    storageBucket: 'shm-app-9927d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAumGGUvN03G0LA4NNYzUqGkIk3Am9U4FE',
    appId: '1:1027150286660:ios:13938349ea6719cb16d111',
    messagingSenderId: '1027150286660',
    projectId: 'shm-app-9927d',
    storageBucket: 'shm-app-9927d.firebasestorage.app',
    iosBundleId: 'com.example.shmApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAumGGUvN03G0LA4NNYzUqGkIk3Am9U4FE',
    appId: '1:1027150286660:ios:13938349ea6719cb16d111',
    messagingSenderId: '1027150286660',
    projectId: 'shm-app-9927d',
    storageBucket: 'shm-app-9927d.firebasestorage.app',
    iosBundleId: 'com.example.shmApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBLDVZESlV9jDfm6wDDXMZytf9FSfECMc',
    appId: '1:1027150286660:web:c06f6189992251a116d111',
    messagingSenderId: '1027150286660',
    projectId: 'shm-app-9927d',
    authDomain: 'shm-app-9927d.firebaseapp.com',
    storageBucket: 'shm-app-9927d.firebasestorage.app',
    measurementId: 'G-B52GFQ24KN',
  );
}
